# fly.toml app configuration file generated for hono-app-2-wandering-waterfall-2608 on 2025-01-13T20:40:58-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'hono-app-2-wandering-waterfall-2608'
primary_region = 'lax'

[build]
  [build.args]
    SENTRY_ORG = "pry0rity"
    SENTRY_PROJECT = "javascript-react"

[env]
  SENTRY_AUTH_TOKEN = ""
  SENTRY_ORG = "pry0rity"
  SENTRY_PROJECT = "javascript-react"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
